# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Voronowledge
baseurl: "/voronowledge" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_rnaka:  RNakanishi
github_filipe:  FilipeCN

safe: false
source:       .
destination:  ~/git/gh-pages-voro/

permalink: /blog/:categories/:year/:month/:day/:title.html
timezone:      null
paginate_path: /blog/page:num
tag_page_dir: /blog/tags
future: false

include: [".nojekyll"]
# exclude:      ["Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown
gems:
  - jekyll-archives
  - jekyll-assets
  - jekyll-gist
  - jekyll-paginate
  - jekyll-archivesa
  - jekyll-toc

safe: false
verbose: true

jekyll-archives:
    enabled: all
    layout: 'archive'
    permalinks:
        year: '/archives/year/:year.html'
        month: '/archives/month/:year-:month.html'
        tag: '/archives/tag/:name.html'
